
-- luacheck: globals GetLocale C_AddOns

if (GetLocale() == "deDE") then
  rgcw = rgcw or {}
  rgcw.L = {}

  rgcw.L["addon_name"] = "CooldownWatch"

  -- console
  rgcw.L["help"] = "|cFFFFC300(%s)|r: Benutze |cFFFFC300/rgcw|r oder |cFFFFC300/cooldownwatch|r "
    .. "für eine Liste der verfügbaren Optionen"
  rgcw.L["reload"] = "|cFFFFC300reload|r - UI neu laden"
  rgcw.L["opt"] = "|cFFFFC300opt|r - Zeige Optionsmenu an"
  rgcw.L["conf"] = "|cFFFFC300conf enable||disable|r - Zeigt oder versteckt die Beispiel-Ziel-Cooldown-Leiste "
    .. "zum Positionieren (bei entsperrter Leiste verschiebbar)"
  rgcw.L["test"] = "|cFFFFFF00test|r - Test-Befehle (nutze |cFFFFC300/rgcw test|r für das vollständige Menü)"
  rgcw.L["info_title"] = "|cFF00FFB0CooldownWatch:|r"
  rgcw.L["invalid_argument"] = "Ungültiges Argument übergeben"
  rgcw.L["update_available"] = "Neue Version |cFFFFC300%s|r ist verfügbar - |cFF00FFB0Update empfohlen!|r"

  -- about tab
  rgcw.L["author"] = "Autor: Michael Wiesendanger"
  rgcw.L["email"] = "E-Mail: michael.wiesendanger@gmail.com"
  rgcw.L["version"] = "Version: " .. C_AddOns.GetAddOnMetadata(RGCW_CONSTANTS.ADDON_NAME, "Version")
  rgcw.L["issues"] = "Probleme: https://github.com/RagedUnicorn/wow-classic-cooldownwatch/issues"

  -- options
  rgcw.L["options_category_name"] = "Optionen"
  rgcw.L["options_title"] = "Optionen"
  rgcw.L["window_lock_target_cooldown_bar"] = "Sperre Zielabklingzeitenbalken"
  rgcw.L["window_lock_target_cooldown_bar_tooltip"] = "Verhindert das bewegen des Zielabklingzeitenbalken"
  rgcw.L["option_global_assume_worst_case"] = "Worst Case für alle Abklingzeiten annehmen"
  rgcw.L["option_global_assume_worst_case_tooltip"] = "Nimmt an, dass jeder Gegner Talente oder Ausrüstung "
    .. "besitzt, die seine Abklingzeiten verkürzen. Worst-Case-Einstellungen einzelner Abklingzeiten "
    .. "haben weiterhin Vorrang."

  -- proximity cooldowns
  rgcw.L["proximity_category_name"] = "Abklingzeiten in der Nähe"
  rgcw.L["proximity_title"] = "Abklingzeiten in der Nähe"
  rgcw.L["option_enable_proximity_cooldown_window"] = "Fenster für Abklingzeiten in der Nähe aktivieren"
  rgcw.L["option_enable_proximity_cooldown_window_tooltip"] = "Zeigt ein bewegliches Fenster mit den "
    .. "laufenden Abklingzeiten von Gegnern in der Nähe, die nicht dein aktuelles Ziel sind"
  rgcw.L["option_hide_long_proximity_cooldowns"] = "Lange Abklingzeiten ausblenden"
  rgcw.L["option_hide_long_proximity_cooldowns_tooltip"] = "Blendet Abklingzeiten über %d Sekunden aus "
    .. "dem Fenster aus. Lange Abklingzeiten entscheiden selten den nächsten Kampf und würden die "
    .. "kurzen verdrängen."
  rgcw.L["proximity_scale_slider_title"] = "Fensterskalierung"
  rgcw.L["proximity_scale_slider_tooltip"] = "Passt die Grösse des Fensters für Abklingzeiten "
    .. "in der Nähe an"
  rgcw.L["proximity_max_displayed_slider_title"] = "Maximal angezeigte Abklingzeiten"
  rgcw.L["proximity_max_displayed_slider_tooltip"] = "Wie viele Abklingzeiten das Fenster gleichzeitig "
    .. "anzeigt. Die zuletzt erkannten Abklingzeiten werden zuerst angezeigt."
  rgcw.L["proximity_place_mode_button"] = "Fenster positionieren"
  rgcw.L["proximity_place_mode_save_button"] = "Speichern"
  rgcw.L["proximity_defaults_button"] = "Auf Standard zurücksetzen"

  -- friendly cooldowns
  rgcw.L["friendly_category_name"] = "Verbündete Abklingzeiten"
  rgcw.L["friendly_title"] = "Verbündete Abklingzeiten"
  rgcw.L["option_track_friendly_cooldowns"] = "Verbündete Abklingzeiten verfolgen"
  rgcw.L["option_track_friendly_cooldowns_tooltip"] = "Verfolgt Abklingzeiten verbündeter Spieler "
    .. "und ihrer Begleiter"
  rgcw.L["option_show_friendly_target_cooldowns"] = "Abklingzeiten verbündeter Ziele anzeigen"
  rgcw.L["option_show_friendly_target_cooldowns_tooltip"] = "Zeigt die verfolgten Abklingzeiten eines "
    .. "verbündeten Ziels auf dem Zielabklingzeitenbalken an"
  rgcw.L["option_enable_friendly_proximity_cooldown_window"] = "Fenster für verbündete Abklingzeiten "
    .. "in der Nähe aktivieren"
  rgcw.L["option_enable_friendly_proximity_cooldown_window_tooltip"] = "Zeigt ein bewegliches Fenster "
    .. "mit den laufenden Abklingzeiten verbündeter Spieler"
  rgcw.L["option_hide_long_friendly_proximity_cooldowns"] = "Lange Abklingzeiten ausblenden"
  rgcw.L["option_hide_long_friendly_proximity_cooldowns_tooltip"] = "Blendet Abklingzeiten über "
    .. "%d Sekunden aus dem Fenster aus"
  rgcw.L["friendly_proximity_scope_title"] = "Bereich"
  rgcw.L["friendly_proximity_scope_tooltip"] = "Welche verbündeten Zauberwirker das Fenster anzeigt: "
    .. "Gruppe, Schlachtzug oder alle"
  rgcw.L["friendly_proximity_scope_group"] = "Gruppe"
  rgcw.L["friendly_proximity_scope_raid"] = "Schlachtzug"
  rgcw.L["friendly_proximity_scope_all"] = "Alle"
  rgcw.L["friendly_scale_slider_title"] = "Fensterskalierung"
  rgcw.L["friendly_scale_slider_tooltip"] = "Passt die Grösse des Fensters für verbündete "
    .. "Abklingzeiten an"
  rgcw.L["friendly_max_displayed_slider_title"] = "Maximal angezeigte Abklingzeiten"
  rgcw.L["friendly_max_displayed_slider_tooltip"] = "Wie viele Abklingzeiten das Fenster "
    .. "gleichzeitig anzeigt"
  rgcw.L["friendly_place_mode_button"] = "Fenster positionieren"
  rgcw.L["friendly_place_mode_save_button"] = "Speichern"
  rgcw.L["friendly_defaults_button"] = "Auf Standard zurücksetzen"

  -- profiles
  rgcw.L["profile_category_name"] = "Profile"
  rgcw.L["profile_title"] = "Profile"
  rgcw.L["profile_list_label"] = "Gespeicherte Profile"
  rgcw.L["profile_string_label"] = "Profil-Zeichenkette (Export / Import)"
  rgcw.L["profile_save_button"] = "Aktuelles speichern als..."
  rgcw.L["profile_apply_button"] = "Anwenden"
  rgcw.L["profile_rename_button"] = "Umbenennen"
  rgcw.L["profile_delete_button"] = "Löschen"
  rgcw.L["profile_export_button"] = "Exportieren"
  rgcw.L["profile_import_button"] = "Importieren"
  rgcw.L["profile_name_prompt"] = "Gib einen Namen für das neue Profil ein:"
  rgcw.L["profile_rename_prompt"] = "Gib einen neuen Namen für das Profil ein:"
  rgcw.L["profile_import_name_prompt"] = "Gib einen Namen ein, unter dem das importierte Profil gespeichert wird:"
  rgcw.L["profile_apply_confirm"] = "Profil \"%s\" anwenden? Dies überschreibt deine aktuellen Einstellungen "
    .. "und lädt die UI neu."
  rgcw.L["profile_delete_confirm"] = "Profil \"%s\" löschen?"
  rgcw.L["profile_save_success"] = "Profil \"%s\" gespeichert"
  rgcw.L["profile_import_success"] = "Profil \"%s\" importiert"
  rgcw.L["profile_delete_success"] = "Profil \"%s\" gelöscht"
  rgcw.L["profile_rename_success"] = "Profil umbenannt in \"%s\""
  rgcw.L["profile_error_empty"] = "Es gibt keine Profil-Zeichenkette zum Importieren"
  rgcw.L["profile_error_invalid"] = "Die Profil-Zeichenkette ist ungültig oder konnte nicht gelesen werden"
  rgcw.L["profile_error_checksum"] = "Die Profil-Zeichenkette ist beschädigt (Prüfsumme stimmt nicht)"
  rgcw.L["profile_error_wrong_addon"] = "Diese Profil-Zeichenkette wurde nicht von CooldownWatch erstellt"
  rgcw.L["profile_error_version"] = "Diese Profil-Zeichenkette wurde mit einer neueren Version "
    .. "von CooldownWatch erstellt"
  rgcw.L["profile_error_name_empty"] = "Der Profilname darf nicht leer sein"
  rgcw.L["profile_error_name_exists"] = "Ein Profil mit diesem Namen existiert bereits"
  rgcw.L["profile_error_name_too_long"] = "Der Profilname darf nicht länger als %d Zeichen sein"
  rgcw.L["profile_error_no_selection"] = "Kein Profil ausgewählt"
  rgcw.L["profile_error_default_cannot_be_deleted"] = "Das Profil \"%s\" kann nicht gelöscht werden"
  rgcw.L["profile_error_default_cannot_be_renamed"] = "Das Profil \"%s\" kann nicht umbenannt werden"
  rgcw.L["profile_error_default_cannot_be_overwritten"] = "Das Profil \"%s\" kann nicht überschrieben werden"

  -- cooldown menu
  rgcw.L["tab_button_enemy"] = "Gegner"
  rgcw.L["tab_button_friendly"] = "Verbündete"
  rgcw.L["category_priest"] = "Priester"
  rgcw.L["category_rogue"] = "Schurke"
  rgcw.L["category_mage"] = "Magier"
  rgcw.L["category_hunter"] = "Jäger"
  rgcw.L["category_warlock"] = "Hexenmeister"
  rgcw.L["category_paladin"] = "Paladin"
  rgcw.L["category_druid"] = "Druide"
  rgcw.L["category_shaman"] = "Shamane"
  rgcw.L["category_warrior"] = "Krieger"
  rgcw.L["category_racials"] = "Rassenfähigkeiten"
  rgcw.L["category_items"] = "Items"
  rgcw.L["category_misc"] = "Diverse"
  rgcw.L["option_assume_worst_case"] = "Worst Case"
  rgcw.L["option_assume_worst_case_tooltip"] = "Nimmt an, dass der Gegner Talente oder Ausrüstung besitzt, "
    .. "die diese Abklingzeit verkürzen. Die Leiste zählt die kürzeste realistische Abklingzeit "
    .. "statt des Grundwerts herunter."
  rgcw.L["option_cooldown_values"] = "%s Abklingzeit"
  rgcw.L["option_cooldown_values_worst_case"] = "%s Worst Case"
  rgcw.L["option_cooldown_values_override"] = "%s Überschreibung (Basis %s)"
  rgcw.L["option_reset_to_default"] = "Auf Standard zurücksetzen"
  rgcw.L["option_reset_to_default_tooltip"] = "Verwirft deinen Wert für dieses Feld und kehrt zum "
    .. "Wert aus dem Zauberkatalog zurück. Wird nur angezeigt, solange das Feld überschrieben ist. "
    .. "Das Feld zu leeren und zu verlassen bewirkt dasselbe."
  rgcw.L["option_cooldown_label"] = "Abklingzeit"
  rgcw.L["option_use_worst_case"] = "Worst Case verwenden"
  rgcw.L["option_manual_cooldown_override"] = "Abklingzeit überschreiben"
  rgcw.L["option_manual_cooldown_override_tooltip"] = "Verfolgt diesen Zauber mit deiner eigenen "
    .. "Abklingzeit in Sekunden statt mit dem Katalogwert. Hat Vorrang vor allen "
    .. "Worst-Case-Einstellungen. Mit Enter oder einem Klick ausserhalb des Feldes übernehmen, "
    .. "mit Escape abbrechen. Feld leeren, um zum Katalogwert zurückzukehren - eine abgeblendete "
    .. "Zahl bedeutet, dass nichts überschrieben ist. Nachkommastellen sind erlaubt (z.B. 12,5); "
    .. "das Maximum sind 60 Minuten."
  rgcw.L["option_worst_case_value_tooltip"] = "Die kürzeste Abklingzeit, die dieser Zauber realistisch "
    .. "haben kann. Wird anstelle der Grundabklingzeit verwendet, solange \"Worst Case verwenden\" "
    .. "aktiv ist. Bearbeiten, um den Katalogwert zu korrigieren. Mit Enter oder einem Klick "
    .. "ausserhalb des Feldes übernehmen, mit Escape abbrechen. Feld leeren, um zum Katalogwert "
    .. "zurückzukehren - eine abgeblendete Zahl bedeutet, dass nichts überschrieben ist. "
    .. "Nachkommastellen sind erlaubt (z.B. 12,5), und der Wert muss unter der Grundabklingzeit "
    .. "des Zaubers liegen."
end
