
-- luacheck: globals C_AddOns

rgcw = rgcw or {}
rgcw.L = {}

rgcw.L["addon_name"] = "CooldownWatch"

-- console
rgcw.L["help"] = "|cFFFFC300(%s)|r: Use |cFFFFC300/rgcw|r or |cFFFFC300/cooldownwatch|r for a list of options"
rgcw.L["reload"] = "|cFFFFC300reload|r - Reload UI"
rgcw.L["opt"] = "|cFFFFC300opt|r - Display Optionsmenu"
rgcw.L["conf"] = "|cFFFFC300conf enable||disable|r - Show or hide the example target cooldown bar "
  .. "for positioning (drag it into place while shown)"
rgcw.L["test"] = "|cFFFFFF00test|r - Test commands (use |cFFFFC300/rgcw test|r for the full menu)"
rgcw.L["info_title"] = "|cFF00FFB0CooldownWatch:|r"
rgcw.L["invalid_argument"] = "Invalid argument passed"
rgcw.L["update_available"] = "New version |cFFFFC300%s|r is available - |cFF00FFB0consider updating!|r"

-- about
rgcw.L["author"] = "Author: Michael Wiesendanger"
rgcw.L["email"] = "E-Mail: michael.wiesendanger@gmail.com"
rgcw.L["version"] = "Version: " .. C_AddOns.GetAddOnMetadata(RGCW_CONSTANTS.ADDON_NAME, "Version")
rgcw.L["issues"] = "Issues: https://github.com/RagedUnicorn/wow-classic-cooldownwatch/issues"

-- options
rgcw.L["options_category_name"] = "Options"
rgcw.L["options_title"] = "Options"
rgcw.L["option_global_assume_worst_case"] = "Assume worst case for all cooldowns"
rgcw.L["option_global_assume_worst_case_tooltip"] = "Assume every enemy has talents or gear reducing "
  .. "their cooldowns. Worst case settings on individual cooldowns still take precedence."
rgcw.L["target_bar_scale_slider_title"] = "Bar scale"
rgcw.L["target_bar_scale_slider_tooltip"] = "Adjust the size of the Targetcooldownbar"
rgcw.L["target_bar_place_mode_button"] = "Position Bar"
rgcw.L["target_bar_place_mode_apply_button"] = "Apply"
rgcw.L["target_bar_defaults_button"] = "Reset to Defaults"

-- proximity cooldowns
rgcw.L["proximity_category_name"] = "Proximity Cooldowns"
rgcw.L["proximity_title"] = "Proximity Cooldowns"
rgcw.L["option_enable_proximity_cooldown_window"] = "Enable Proximity Cooldown Window"
rgcw.L["option_enable_proximity_cooldown_window_tooltip"] = "Show a movable window listing the active "
  .. "cooldowns of nearby enemies other than your current target"
rgcw.L["option_hide_long_proximity_cooldowns"] = "Hide long cooldowns"
rgcw.L["option_hide_long_proximity_cooldowns_tooltip"] = "Hide cooldowns longer than %d seconds from "
  .. "the window. Long cooldowns rarely decide the next engagement and would crowd out the short ones."
rgcw.L["proximity_scale_slider_title"] = "Window scale"
rgcw.L["proximity_scale_slider_tooltip"] = "Adjust the size of the Proximity Cooldown Window"
rgcw.L["proximity_max_displayed_slider_title"] = "Maximum displayed cooldowns"
rgcw.L["proximity_max_displayed_slider_tooltip"] = "How many cooldowns the window displays at once. "
  .. "The most recently detected cooldowns are shown first."
rgcw.L["proximity_place_mode_button"] = "Position Window"
rgcw.L["proximity_place_mode_apply_button"] = "Apply"
rgcw.L["proximity_defaults_button"] = "Reset to Defaults"

-- friendly cooldowns
rgcw.L["friendly_category_name"] = "Friendly Cooldowns"
rgcw.L["friendly_title"] = "Friendly Cooldowns"
rgcw.L["option_track_friendly_cooldowns"] = "Track Friendly Cooldowns"
rgcw.L["option_track_friendly_cooldowns_tooltip"] = "Track cooldowns of friendly players and their pets"
rgcw.L["option_show_friendly_target_cooldowns"] = "Show Friendly Target Cooldowns"
rgcw.L["option_show_friendly_target_cooldowns_tooltip"] = "Show a friendly target's tracked cooldowns "
  .. "on the target cooldown bar"
rgcw.L["option_enable_friendly_proximity_cooldown_window"] = "Enable Friendly Proximity Cooldown Window"
rgcw.L["option_enable_friendly_proximity_cooldown_window_tooltip"] = "Show a movable window listing "
  .. "the active cooldowns of friendly players"
rgcw.L["option_hide_long_friendly_proximity_cooldowns"] = "Hide long cooldowns"
rgcw.L["option_hide_long_friendly_proximity_cooldowns_tooltip"] = "Hide cooldowns longer than "
  .. "%d seconds from the window"
rgcw.L["friendly_proximity_scope_title"] = "Scope"
rgcw.L["friendly_proximity_scope_tooltip"] = "Which friendly casters the window lists: "
  .. "your group, your raid or all tracked"
rgcw.L["friendly_proximity_scope_group"] = "Group"
rgcw.L["friendly_proximity_scope_raid"] = "Raid"
rgcw.L["friendly_proximity_scope_all"] = "All"
rgcw.L["friendly_scale_slider_title"] = "Window scale"
rgcw.L["friendly_scale_slider_tooltip"] = "Adjust the size of the Friendly Proximity Cooldown Window"
rgcw.L["friendly_max_displayed_slider_title"] = "Maximum displayed cooldowns"
rgcw.L["friendly_max_displayed_slider_tooltip"] = "How many cooldowns the window displays at once"
rgcw.L["friendly_place_mode_button"] = "Position Window"
rgcw.L["friendly_place_mode_apply_button"] = "Apply"
rgcw.L["friendly_defaults_button"] = "Reset to Defaults"

-- profiles
rgcw.L["profile_category_name"] = "Profiles"
rgcw.L["profile_title"] = "Profiles"
rgcw.L["profile_list_label"] = "Saved Profiles"
rgcw.L["profile_string_label"] = "Profile String (Export / Import)"
rgcw.L["profile_save_button"] = "Save current as..."
rgcw.L["profile_apply_button"] = "Apply"
rgcw.L["profile_rename_button"] = "Rename"
rgcw.L["profile_delete_button"] = "Delete"
rgcw.L["profile_export_button"] = "Export"
rgcw.L["profile_import_button"] = "Import"
rgcw.L["profile_name_prompt"] = "Enter a name for the new profile:"
rgcw.L["profile_rename_prompt"] = "Enter a new name for the profile:"
rgcw.L["profile_import_name_prompt"] = "Enter a name to save the imported profile under:"
rgcw.L["profile_apply_confirm"] = "Apply profile \"%s\"? This overwrites your current settings and reloads the UI."
rgcw.L["profile_delete_confirm"] = "Delete profile \"%s\"?"
rgcw.L["profile_save_success"] = "Saved profile \"%s\""
rgcw.L["profile_import_success"] = "Imported profile \"%s\""
rgcw.L["profile_delete_success"] = "Deleted profile \"%s\""
rgcw.L["profile_rename_success"] = "Renamed profile to \"%s\""
rgcw.L["profile_error_empty"] = "There is no profile string to import"
rgcw.L["profile_error_invalid"] = "The profile string is invalid or could not be read"
rgcw.L["profile_error_checksum"] = "The profile string is corrupt (checksum mismatch)"
rgcw.L["profile_error_wrong_addon"] = "This profile string was not created by CooldownWatch"
rgcw.L["profile_error_version"] = "This profile string was created by a newer version of CooldownWatch"
rgcw.L["profile_error_name_empty"] = "The profile name cannot be empty"
rgcw.L["profile_error_name_exists"] = "A profile with that name already exists"
rgcw.L["profile_error_name_too_long"] = "The profile name cannot be longer than %d characters"
rgcw.L["profile_error_no_selection"] = "No profile selected"
rgcw.L["profile_error_default_cannot_be_deleted"] = "The \"%s\" profile cannot be deleted"
rgcw.L["profile_error_default_cannot_be_renamed"] = "The \"%s\" profile cannot be renamed"
rgcw.L["profile_error_default_cannot_be_overwritten"] = "The \"%s\" profile cannot be overwritten"

-- cooldown menu
rgcw.L["tab_button_enemy"] = "Enemy"
rgcw.L["tab_button_friendly"] = "Friendly"
rgcw.L["category_priest"] = "Priest"
rgcw.L["category_rogue"] = "Rogue"
rgcw.L["category_mage"] = "Mage"
rgcw.L["category_hunter"] = "Hunter"
rgcw.L["category_warlock"] = "Warlock"
rgcw.L["category_paladin"] = "Paladin"
rgcw.L["category_druid"] = "Druid"
rgcw.L["category_shaman"] = "Shaman"
rgcw.L["category_warrior"] = "Warrior"
rgcw.L["category_racials"] = "Racials"
rgcw.L["category_items"] = "Items"
rgcw.L["category_misc"] = "Misc"
rgcw.L["option_assume_worst_case"] = "Worst case"
rgcw.L["option_assume_worst_case_tooltip"] = "Assume the enemy has talents or gear reducing this cooldown. "
  .. "The bar counts down the shortest realistic cooldown instead of the base value."
--[[
  Segments of the spell row's description line - joined with " / " and coloured
  individually (see CooldownMenu.BuildCooldownValueSegments), so each one takes
  a single value.
]]--
rgcw.L["option_cooldown_values"] = "%s cooldown"
rgcw.L["option_cooldown_values_worst_case"] = "%s worst case"
rgcw.L["option_cooldown_values_override"] = "%s override (base %s)"
rgcw.L["option_reset_to_default"] = "Reset to default"
rgcw.L["option_reset_to_default_tooltip"] = "Discard your value for this field and go back to the "
  .. "one from the spell catalog. Shown only while the field is overridden. "
  .. "Emptying the box and leaving it does the same thing."
rgcw.L["option_cooldown_label"] = "Cooldown"
rgcw.L["option_use_worst_case"] = "Use worst case"
rgcw.L["option_manual_cooldown_override"] = "Cooldown override"
rgcw.L["option_manual_cooldown_override_tooltip"] = "Track this spell with your own cooldown in seconds "
  .. "instead of the catalog value. Takes precedence over all worst case settings. "
  .. "Press Enter or click outside the box to apply, Escape to cancel. "
  .. "Empty the box to go back to the catalog value - a dimmed number means nothing is overridden. "
  .. "Fractions are allowed (e.g. 12.5); the maximum is 60 minutes."
rgcw.L["option_worst_case_value_tooltip"] = "The shortest cooldown this spell can realistically have. "
  .. "Used instead of the base cooldown while \"Use worst case\" is enabled. Edit it to correct the "
  .. "catalog value. Press Enter or click outside the box to apply, Escape to cancel. "
  .. "Empty the box to go back to the catalog value - a dimmed number means nothing is overridden. "
  .. "Fractions are allowed (e.g. 12.5), and the value must be below the spell's base cooldown."
