name: Headless Tests
on:
  push:
    branches: [master]
  pull_request:

jobs:
  test-headless:
    runs-on: ubuntu-latest
    name: Headless busted specs
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Busted for lua codebases
        uses: RagedUnicorn/action-busted@v1
